import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createOpening,connectionPath} from '../dist/prototypes/ask-your-data-6d2.js';
function harness(reduced=false){let time=0,id=0;const pending=new Map(),changes=[];const c=createOpening({onChange:s=>changes.push(s),reduced:()=>reduced,now:()=>time,schedule:(fn,delay)=>{pending.set(++id,{fn,delay});return id;},cancel:id=>pending.delete(id)});return {c,pending,changes,advance:n=>time+=n,tick(){assert.equal(pending.size,1);const [id,{fn,delay}]=[...pending][0];time+=delay;pending.delete(id);fn();}};}
test('opening requires ASK, then four partial responses, then stops without CONNECT',()=>{const h=harness();assert.equal(h.pending.size,0);h.c.ask();h.c.ask();assert.equal(h.pending.size,1);for(let i=1;i<=4;i++){h.tick();assert.equal(h.c.snapshot().received,i);assert.equal(h.c.snapshot().phase,'sending');}h.tick();assert.deepEqual(h.c.snapshot(),{phase:'scattered',received:4,paused:false});h.c.ask();assert.equal(h.pending.size,0);});
test('repeated restart cancels all progress and stale callbacks including during a new run',()=>{const h=harness();h.c.ask();const stale=[...h.pending.values()][0].fn;h.tick();h.c.reset();h.c.reset();h.c.ask();stale();assert.equal(h.c.snapshot().received,0);assert.equal(h.pending.size,1);h.c.reset();assert.deepEqual(h.c.snapshot(),{phase:'ready',received:0,paused:false});assert.equal(h.pending.size,0);});
test('hidden tab pauses with remaining time and resumes without duplicate timers',()=>{const h=harness();h.c.ask();h.advance(400);h.c.pause();h.c.pause();assert.equal(h.pending.size,0);h.c.resume();h.c.resume();assert.equal([...h.pending.values()][0].delay,600);h.tick();assert.equal(h.c.snapshot().received,1);});
test('reduced motion reveals the same result immediately, including preference change mid-run',()=>{const h=harness(true);h.c.ask();assert.equal(h.c.snapshot().phase,'scattered');assert.equal(h.pending.size,0);const k=harness();k.c.ask();k.c.reduceMotion();assert.equal(k.c.snapshot().received,4);assert.equal(k.pending.size,0);});
test('disposing cancels callbacks and further interactions',()=>{const h=harness();h.c.ask();const stale=[...h.pending.values()][0].fn;h.c.dispose();stale();h.c.ask();h.c.reset();assert.equal(h.pending.size,0);assert.equal(h.c.snapshot().received,0);});
test('desktop and recomposed mobile paths share actual question origin and system endpoint',()=>{const origin={x:181,y:142},target={x:269,y:410};for(const options of [{},{lowerRow:true,edge:340}]){const path=connectionPath(origin,target,options);assert.ok(path.startsWith('M181 142'));assert.ok(path.endsWith('269 410'));}assert.match(connectionPath(origin,target,{lowerRow:true,edge:340}),/L340 398/);});
test('preview has semantic controls, initially hidden signals, distinct source art and isolated assets',()=>{const h=readFileSync(new URL('../dist/prototypes/ask-your-data-6d2.html',import.meta.url),'utf8'),css=readFileSync(new URL('../dist/prototypes/ask-your-data-6d2-art.css',import.meta.url),'utf8');assert.match(h,/<h1>WHY DID SALES DECLINE/);assert.equal((h.match(/class="signal" hidden/g)||[]).length,4);assert.match(h,/id="restart" type="button"/);assert.match(h,/SIMULATION \/ EXAMPLE DATA/);assert.doesNotMatch(h,/app.js|data-dq|CONNECT →|A SIMPLE/);assert.doesNotMatch(css,/\.links\s*\{\s*display:\s*none/);assert.match(css,/prefers-reduced-motion/);assert.match(css,/focus-visible/);});
